import React from 'react'
import styled from '@emotion/styled';
import Head from 'next/head'


type LayoutProps = {
    children: React.ReactNode
}

const Layout = ({ children }: LayoutProps) => {
    return (
        <>
            <Head>
                <title>여기 덕담이요</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper>
                {children}
            </Wrapper>
        </>
    )
}

export default Layout

const Wrapper = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
    margin: auto;
    max-width:480px ;
    width: 100%;
    height: 100vh;
    background-color: ${({ theme }) => theme.color.dark};
`
